SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE `btx_alerts` ( `id` int(11) unsigned NOT NULL AUTO_INCREMENT, `title` varchar(255) DEFAULT NULL, `description` text, `link` varchar(255) DEFAULT NULL, `archived` char(2) NOT NULL, `last_updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, `internal_notes` text, `start_date` datetime DEFAULT NULL, `end_date` datetime DEFAULT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `btx_events_categories` ( `id` int(11) NOT NULL AUTO_INCREMENT, `parent` int(11) DEFAULT NULL, `name` varchar(255) NOT NULL DEFAULT '', `route` varchar(255) NOT NULL DEFAULT '', `position` int(11) NOT NULL, PRIMARY KEY (`id`), KEY `parent` (`parent`), KEY `route` (`route`), KEY `position` (`position`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `btx_events_date_cache` ( `id` int(11) NOT NULL AUTO_INCREMENT, `event` int(11) NOT NULL, `start` datetime NOT NULL, `end` datetime NOT NULL, `date_cached` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, `title_route` varchar(255) NOT NULL DEFAULT '', `date_route` varchar(255) NOT NULL DEFAULT '', PRIMARY KEY (`id`), KEY `event` (`event`), KEY `start` (`start`), KEY `end` (`end`), KEY `title_route` (`title_route`), KEY `date_route` (`date_route`), KEY `date_cached` (`date_cached`), CONSTRAINT `btx_events_date_cache_ibfk_1` FOREIGN KEY (`event`) REFERENCES `btx_events_events` (`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `btx_events_event_categories` ( `event` int(11) NOT NULL, `category` int(11) NOT NULL, KEY `event` (`event`), KEY `category` (`category`), CONSTRAINT `btx_events_event_categories_ibfk_1` FOREIGN KEY (`event`) REFERENCES `btx_events_events` (`id`) ON DELETE CASCADE, CONSTRAINT `btx_events_event_categories_ibfk_2` FOREIGN KEY (`category`) REFERENCES `btx_events_categories` (`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `btx_events_events` ( `id` int(11) NOT NULL AUTO_INCREMENT, `title` varchar(255) NOT NULL DEFAULT '', `blurb` text NOT NULL, `content` mediumtext NOT NULL, `image` varchar(255) NOT NULL, `location` varchar(255) NOT NULL DEFAULT '', `link` varchar(255) NOT NULL DEFAULT '', `in_content_callouts` longtext NOT NULL, `full_width_callouts` longtext NOT NULL, `start_date` date DEFAULT NULL, `end_date` date DEFAULT NULL, `start_time` time DEFAULT NULL, `end_time` time DEFAULT NULL, `all_day` char(2) NOT NULL, `recurrence_type` varchar(255) NOT NULL, `recurrence_detail` varchar(255) NOT NULL, `canceled_recurrences` text NOT NULL, `recurring_end_date` date DEFAULT NULL, `last_updated` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP, `featured` char(2) NOT NULL, `route` varchar(255) DEFAULT NULL, PRIMARY KEY (`id`), KEY `start_date` (`start_date`), KEY `end_date` (`end_date`), KEY `recurring_end_date` (`recurring_end_date`), KEY `recurrence_type` (`recurrence_type`), KEY `featured` (`featured`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `btx_form_builder_entries` ( `id` int(11) NOT NULL AUTO_INCREMENT, `form` int(11) NOT NULL, `data` longtext NOT NULL, `created_at` datetime NOT NULL DEFAULT '0000-00-00 00:00:00', PRIMARY KEY (`id`), KEY `form` (`form`), CONSTRAINT `btx_form_builder_entries_ibfk_1` FOREIGN KEY (`form`) REFERENCES `btx_form_builder_forms` (`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `btx_form_builder_fields` ( `id` int(11) NOT NULL AUTO_INCREMENT, `form` int(11) NOT NULL, `column` int(11) NOT NULL, `alignment` char(5) NOT NULL, `type` varchar(255) NOT NULL DEFAULT '', `data` longtext NOT NULL, `position` int(11) NOT NULL, PRIMARY KEY (`id`), KEY `form` (`form`), KEY `column` (`column`), KEY `position` (`position`), CONSTRAINT `btx_form_builder_fields_ibfk_1` FOREIGN KEY (`form`) REFERENCES `btx_form_builder_forms` (`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `btx_form_builder_forms` ( `id` int(11) NOT NULL AUTO_INCREMENT, `title` varchar(255) NOT NULL DEFAULT '', `paid` char(2) NOT NULL DEFAULT '', `base_price` float NOT NULL, `early_bird_base_price` float NOT NULL, `early_bird_date` datetime DEFAULT NULL, `total_collected` float NOT NULL, `entries` int(11) NOT NULL, `limit_entries` char(2) NOT NULL DEFAULT '', `max_entries` int(11) NOT NULL, `scheduling` char(2) NOT NULL, `scheduling_open_date` datetime DEFAULT NULL, `scheduling_close_date` datetime DEFAULT NULL, `scheduling_before_message` longtext, `scheduling_after_message` longtext, `last_entry` datetime DEFAULT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `btx_news` ( `id` int(11) unsigned NOT NULL AUTO_INCREMENT, `date` date NOT NULL, `title` varchar(255) NOT NULL DEFAULT '', `blurb` text NOT NULL, `content` text NOT NULL, `in_content_callouts` longtext NOT NULL, `full_width_callouts` longtext NOT NULL, `image` varchar(255) NOT NULL DEFAULT '', `external_link` varchar(255) NOT NULL DEFAULT '', `featured` char(2) NOT NULL, `route` varchar(255) NOT NULL DEFAULT '', PRIMARY KEY (`id`), KEY `featured` (`featured`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `btx_news_categories` ( `id` int(11) unsigned NOT NULL AUTO_INCREMENT, `title` varchar(255) NOT NULL DEFAULT '', `hidden` char(2) NOT NULL DEFAULT '', `position` int(11) NOT NULL, `route` varchar(255) NOT NULL DEFAULT '', PRIMARY KEY (`id`), KEY `position` (`position`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `btx_news_categories_rel` ( `news` int(11) unsigned NOT NULL, `category` int(11) unsigned NOT NULL, KEY `news` (`news`), KEY `category` (`category`), CONSTRAINT `btx_news_categories_rel_ibfk_1` FOREIGN KEY (`news`) REFERENCES `btx_news` (`id`) ON DELETE CASCADE, CONSTRAINT `btx_news_categories_rel_ibfk_2` FOREIGN KEY (`category`) REFERENCES `btx_news_categories` (`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `btx_reusable_callouts` ( `id` int(11) unsigned NOT NULL AUTO_INCREMENT, `type` varchar(255) DEFAULT NULL, `title` varchar(255) DEFAULT NULL, `data` longtext, `archived` char(2) NOT NULL DEFAULT '', PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

SET FOREIGN_KEY_CHECKS=1;